### ISSUE TITLE
Example: laravel app

### ISSUE THREAD

**Issue by f3l1x** [juicyfx/vercel-php#20]

**Comment by CraftLogan** [comment]
Hello, I am working on getting this up and running on laravel but when I run now dev I am stuck with this error PHP process errored Error: spawn php-cgi ENOENT
<img width="1088" ### alt="Screen Shot 2019-08-22 at 11 30 20 AM" src="https://user-images.githubusercontent.com/10950466/63528077-47e5e080-c4d0-11e9-80a0-f1e84c017ddf.pn

**Comment by CraftLogan** [comment]
If anyone has any advice that would be great. Thanks Logan

**Comment by f3l1x** [comment]
You need to install php locally on your computer. Also `php-cgi` binary.

**Comment by AGDholo** [comment]
Laravel default cache to '/storage' folder.This is different from the directory on the now.sh server.
I tried to rewrite StoragePath to '/tmp' but it failed.

**Comment by f3l1x** [comment]
Hello @AGDholo. Only writable folder is /tmp, so you must rewrite all cache folders, session folder and other folders where laravel could write.

**Comment by AGDholo** [comment]
I solved the problem with the /tmp folder, just add the following code in bootstrap/app.php to override StoragePath.

~~~php
# new storage path
# base_path() -> returns root path
$path_storage = "/tmp";

# override already $app->storagePath using the function
$app->useStoragePath($path_storage);
~~~
And set path in config/{cache.php, session.php, view.php}:
`storage_path(xxxx) to storage_path()`

But when I deploy it on the server, it throws an error: `Uncaught ReflectionException: Class translator does not exist in`.

The complete error is as follows:

~~~text
127.0.0.1:37160 [500]: /var/task/user/public /index.php - Uncaught ReflectionException: Class translator does not exist in /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
Stack trace:
#0 /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php(804): ReflectionClass->__construct('translator')
#1 /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\Container\Container->build('translator')
#2 /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\Container\Container->resolve('translator', Array)
#3 /var/task/user/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\Container\Container->make('translator', Array)
#4 /var/task/user/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(121): Illuminate\Foundation\Application->make('translator', Array)
#5 /var/task/user/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(878): app('translator')
#6 /var/task/user/vendor/laravel/framewor in /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 806
~~~

Build warnning:

~~~text

PHP Warning:  PHP Startup: Unable to load dynamic library 'gd' (tried: /tmp/1245e456561ac6e4/.build-utils/.builder/node_modules/@now-php/lib-73/native/php/modules/gd (/tmp/1245e456561ac6e4/.build-utils/.builder/node_modules/@now-php/lib-73/native/php/modules/gd: cannot open shared object file: No such file or directory), /tmp/1245e456561ac6e4/.build-utils/.builder/node_modules/@now-php/lib-73/native/php/modules/gd.so (libX11.so.6: cannot open shared object file: No such file or directory)) in Unknown on line 0
--
02:37:06 AM | PHP Warning:  PHP Startup: Unable to load dynamic library 'xsl' (tried: /tmp/1245e456561ac6e4/.build-utils/.builder/node_modules/@now-php/lib-73/native/php/modules/xsl (/tmp/1245e456561ac6e4/.build-utils/.builder/node_modules/@now-php/lib-73/native/php/modules/xsl: cannot open shared object file: No such file or directory), /tmp/1245e456561ac6e4/.build-utils/.builder/node_modules/@now-php/lib-73/native/php/modules/xsl.so (libexslt.so.0: cannot open shared object file: No such file or directory)) in Unknown on line 0
~~~

I tried to deploy Lumen(not Laravel) on now.sh and everything went well. If anyone knows the solution, please reply.

**Comment by CraftLogan** [comment]
@AGDholo could you post your now.json file. Thanks

**Comment by AGDholo** [comment]
@CraftLogan visit: https://gist.github.com/AGDholo/492ec681a568cdbc38111b8849392282

**Comment by f3l1x** [comment]
Ref: https://github.com/zeit/docs/issues/508

**Comment by f3l1x** [comment]
Laravel example is included in https://github.com/juicyfx/vercel-examples
