### ISSUE TITLE
OctoberCMS deployment error

### ISSUE THREAD

**Issue by fydy** [juicyfx/vercel-php#61]
OctoberCMS deployment error, error details are as follows:
```
11:55:57.022  Retrieving list of deployment files...
11:55:59.059  Downloading 8613 deployment files...
11:56:36.179  Installing build runtime...
11:56:39.304  Build runtime installed: 3125.472ms
11:56:39.641  Looking up build cache...
11:56:39.679  Build cache not found
11:56:44.229  FetchError: request to https://dmmcy0pwk6bqi.cloudfront.net/72fa93338474b73727a4d70b0c643da5286a38f8 failed, reason: getaddrinfo EBUSY dmmcy0pwk6bqi.cloudfront.net
11:56:44.229      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:85863:11)
11:56:44.229      at ClientRequest.emit (events.js:310:20)
11:56:44.229      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:44.229      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:44.229      at TLSSocket.emit (events.js:310:20)
11:56:44.229      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:44.230      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:44.230      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:44.230      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:44.230    message: 'request to https://dmmcy0pwk6bqi.cloudfront.net/72fa93338474b73727a4d70b0c643da5286a38f8 failed, reason: getaddrinfo EBUSY dmmcy0pwk6bqi.cloudfront.net',
11:56:44.230    type: 'system',
11:56:44.230    errno: 'EBUSY',
11:56:44.230    code: 'EBUSY'
11:56:44.230  }
11:56:44.238  [bld_i9i60y1sk] [now] retrying to patch after FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:44.238      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:44.238      at ClientRequest.emit (events.js:310:20)
11:56:44.238      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:44.238      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:44.238      at TLSSocket.emit (events.js:310:20)
11:56:44.238      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:44.238      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:44.238      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:44.238      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:44.238    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:44.239    type: 'system',
11:56:44.239    errno: 'EBUSY',
11:56:44.239    code: 'EBUSY'
11:56:44.239  }
11:56:45.241  [bld_i9i60y1sk] [now] retrying to patch after FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:45.241      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:45.241      at ClientRequest.emit (events.js:310:20)
11:56:45.241      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:45.241      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:45.241      at TLSSocket.emit (events.js:310:20)
11:56:45.241      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:45.241      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:45.241      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:45.241      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:45.241    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:45.241    type: 'system',
11:56:45.242    errno: 'EBUSY',
11:56:45.242    code: 'EBUSY'
11:56:45.242  }
11:56:47.244  [bld_i9i60y1sk] [now] retrying to patch after FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:47.244      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:47.244      at ClientRequest.emit (events.js:310:20)
11:56:47.244      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:47.244      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:47.244      at TLSSocket.emit (events.js:310:20)
11:56:47.244      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:47.244      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:47.244      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:47.244      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:47.244    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:47.244    type: 'system',
11:56:47.244    errno: 'EBUSY',
11:56:47.244    code: 'EBUSY'
11:56:47.244  }
11:56:51.247  FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:51.247      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:51.247      at ClientRequest.emit (events.js:310:20)
11:56:51.247      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:51.247      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:51.247      at TLSSocket.emit (events.js:310:20)
11:56:51.247      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:51.247      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:51.247      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:51.247      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:51.247    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:51.247    type: 'system',
11:56:51.247    errno: 'EBUSY',
11:56:51.247    code: 'EBUSY'
11:56:51.247  }
11:56:51.248  [bld_i9i60y1sk] [now] retrying to patch after FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:51.248      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:51.248      at ClientRequest.emit (events.js:310:20)
11:56:51.248      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:51.248      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:51.248      at TLSSocket.emit (events.js:310:20)
11:56:51.248      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:51.248      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:51.248      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:51.248      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:51.248    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:51.248    type: 'system',
11:56:51.248    errno: 'EBUSY',
11:56:51.248    code: 'EBUSY'
11:56:51.248  }
11:56:52.249  [bld_i9i60y1sk] [now] retrying to patch after FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:52.249      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:52.249      at ClientRequest.emit (events.js:310:20)
11:56:52.249      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:52.249      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:52.249      at TLSSocket.emit (events.js:310:20)
11:56:52.249      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:52.249      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:52.249      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:52.249      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:52.249    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:52.249    type: 'system',
11:56:52.249    errno: 'EBUSY',
11:56:52.249    code: 'EBUSY'
11:56:52.249  }
11:56:54.251  [bld_i9i60y1sk] [now] retrying to patch after FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:54.251      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:54.251      at ClientRequest.emit (events.js:310:20)
11:56:54.251      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:54.251      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:54.251      at TLSSocket.emit (events.js:310:20)
11:56:54.251      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:54.251      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:54.251      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:54.251      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:54.251    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:54.251    type: 'system',
11:56:54.251    errno: 'EBUSY',
11:56:54.251    code: 'EBUSY'
11:56:54.251  }
11:56:58.255  worker main FetchError: request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com
11:56:58.255      at ClientRequest.<anonymous> (/var/task/sandbox-worker.js:4408:11)
11:56:58.255      at ClientRequest.emit (events.js:310:20)
11:56:58.255      at ClientRequest.EventEmitter.emit (domain.js:482:12)
11:56:58.255      at TLSSocket.socketErrorListener (_http_client.js:426:9)
11:56:58.255      at TLSSocket.emit (events.js:310:20)
11:56:58.255      at TLSSocket.EventEmitter.emit (domain.js:482:12)
11:56:58.255      at emitErrorNT (internal/streams/destroy.js:92:8)
11:56:58.255      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11:56:58.255      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
11:56:58.255    message: 'request to https://api-pdx1.vercel.com/v2/now/deployments/dpl_AnxCrBTB9XtBFm8Ews4ZZvGB9rju/builds/bld_i9i60y1sk failed, reason: getaddrinfo EBUSY api-pdx1.vercel.com',
11:56:58.256    type: 'system',
11:56:58.256    errno: 'EBUSY',
11:56:58.256    code: 'EBUSY'
11:56:58.256  }
11:56:59.587  Done with "api/index.php"
```

**Comment by f3l1x** [comment]
Hello @fydy. Could you show me MVP repository?

**Comment by fydy** [comment]
@f3l1x The repository is https://github.com/fydy/oc

**Comment by f3l1x** [comment]
Could you keep there only must-have files? I mean remove all unused or unrelated stuff? Also include now.json.

**Comment by fydy** [comment]
I set up a website locally by laragon , An error occurred while trying to deploy through zeit. My build logs https://vercel.com/fydy/oc/43cdz7n96

**Comment by f3l1x** [comment]
Hi @fydy. Thanks for tryout.

I see a few problems:

1. Vendor should be ignored in nowignore or vercelignore file.
2. Vendor has over 70MB, lambda limit is 50MB.
3. OctoberCMS needs DB, right? 
4. I don't think that OctoberCMS fits great to lambda. My point of view.

However, I prepare a PR to my vercel-examples repo. 

https://github.com/juicyfx/vercel-examples/pull/12
